alias zshconfig="nvim ~/dotfiles/.zshrc"
alias nvimconfig="nvim ~/dotfiles/nvim"
alias tree2="tree -L 2"
alias tree3="tree -L 3"
alias tree4="tree -L 4"
alias starconfig="nvim ~/dotfiles/starship.toml"
alias runmongo="mongod --config /opt/homebrew/etc/mongod.conf --fork"
alias restart="exec zsh -l"
alias reboot="sudo shutdown -r now"
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'