format = """
$username\
$directory\
$git_status\
$all\
$character\
"""

right_format = """$cmd_duration"""

# Inserts a blank line between shell prompts
add_newline = false

# Making a single line prompt
[line_break]
disabled = true

[character] # The name of the module we are configuring is "character"
success_symbol = "[>](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[X](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Adding Battery status to the prompt
[battery]
disabled = true
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]] # "bold yellow" style and 💦 symbol when capacity is between 10% and 30%
threshold = 20
style = "yellow"
discharging_symbol = "💀 "

# Setting Icons for git status
[git_status]
# style = "bold white"
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = ""
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

#style = "bold red"
#conflicted = "✗"
#ahead = ""
#behind = ""
#diverged = "✗"
#up_to_date = ""
#untracked = ""
#stashed = "✗"
#modified = "✗"
#staged = "✗"
#renamed = ""
#deleted = ""
##ahead = "⇡${count}"
##diverged = "⇕⇡${ahead_count}⇣${behind_count}"
##behind = "⇣${count}"
## format='([$all_status$ahead_behind]($style) )'
#format='([$all_status]($style) )'
disabled = false

# Setting sudo icon

#[sudo]
#style = "bold green"
#symbol = "👩‍💻 "
#symbol = "🧙"
#disabled = false


# Setting time on the prompt

[time]
disabled = true
format = ' [\[ $time \]]($style) '
time_format = "%T"
#utc_time_offset = "-5"
time_range = "00:00:00-24:00:00"
use_12hr = false
style = "bold green"
#time = 10:03:16

[cmd_duration]
min_time = 500
format = "[$duration](bold yellow)"

[hostname]
ssh_only = false
# format = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
format = "[$hostname](bold red) "
# trim_at = ".companyname.com"
disabled = true

[username]
#style_user = "white bold"
style_user = "yellow"
style_root = "red"
format = "[$user ]($style)"
disabled = false
show_always = true

[aws]
disabled = true
symbol = "  "

[conda]
disabled = true
symbol = " "

[cmake]
disabled = true

[cobol]
disabled = true

[dart]
disabled = true
symbol = " "

[directory]
truncation_length = 1
home_symbol = "~"
style = "white"

[docker_context]
disabled = true
symbol = " "

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[git_branch]
symbol = " "
# format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold italic red"
format = "[git:](bold blue)[\\(](bold blue)[$branch(:$remote_branch)]($style)[\\)](bold blue) "

[golang]
disabled = true
symbol = " "

[haskell]
disabled = true

[hg_branch]
disabled = true
symbol = " "

[java]
disabled = true
symbol = " "

[julia]
disabled = true
symbol = " "

[memory_usage]
disabled = true
symbol = " "

[nim]
disabled = true
symbol = " "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
disabled = false
symbol = " "

#[package]
#symbol = " "

[perl]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[python]
disabled = false
symbol = "🐍 "

[ruby]
disabled = false
symbol = " "

[rust]
disabled = true
symbol = " "

[scala]
disabled = true
symbol = " "

[shlvl]
disabled = true
symbol = " "

[swift]
disabled = true
symbol = "ﯣ "

[lua]
disabled = true
